[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [[redirects]]
  from = "/"
  to = "/ru"
  status = 301
  force = false
  query = {path = "/"}
  conditions = {Language = ["en","ru"], Country = ["US"]}